"""Re-initialize migrations and apply timezone support to Entrevista

Revision ID: c1f38eb5b5ac
Revises: 
Create Date: 2026-02-09 19:59:50.064397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f38eb5b5ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrevista', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_column('hora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrevista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.VARCHAR(length=10), nullable=False))
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
