"""Add documento_id FK to evento_recluta

Revision ID: e8c6d73817bb
Revises: c1f38eb5b5ac
Create Date: 2026-02-16 17:09:54.087235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c6d73817bb'
down_revision = 'c1f38eb5b5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_recluta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_evento_recluta_documento_id', 'documento', ['documento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_recluta', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evento_recluta_documento_id', type_='foreignkey')
        batch_op.drop_column('documento_id')

    # ### end Alembic commands ###
